Refactor
AlexZav1327/guess-game pull request #3
Opened 2023-07-10 10:29 UTC by AlexZav1327

2023-07-11 07:45 UTC, gerladeno commented on main.go
> +				g.processMessage(&target, &guess, update)
не понял, зачем ты передаёшь указатели. Скопировать инт, думаю, будет так же быстро, как скопировать и указатель (или быстрее). Но зато есть два минуса у твоего решения:
- ты добавил работу сборщику мусора
- ты ввёл в заблуждение читающего (потому что у меня от прочтения такого кода возникло ощущение, что ты эти значения в вызванном методе будешь менять)

2023-07-11 07:45 UTC, gerladeno commented on main.go
> +				g.processCallbackQuery(&target, update)
аналогично

2023-07-11 07:50 UTC, gerladeno commented on main.go
> +		fmt.Println("Error converting user response to integer:", err)
в продакшн коде ты нигде не встретишь использование fmt.Print
если хочешь что-то написать в лог, используй логгер.
Но следом возникает такой вопрос. Логи - это то, что читает программист, чтоб разобраться в проблеме. Зачем программисту знать про то, что пользователь ввёл вместо 67 кфшгмтзшкгт? Это совершенно мусорная информация. Так что или не пиши её никуда, или пиши о проблеме самому пользователю - в телегу.
Ну и выключать сервис (о чём ты спросил) просто потому, что пользователь что-то неправильно ввёл - это совсем странная затея

2023-07-11 07:52 UTC, gerladeno commented on main.go
> +	case convertUserMessageToInt(userMessage) == *target:
не очень эффективный подход. Если у тебя действительно выполняется условие ==, то функция convertUserMessageToInt выполнится 3 раза. Лучше вызвать её один раз в начале и потом просто проверять значения

2023-07-11 07:54 UTC, gerladeno commented on main.go
> +				g.processMessage(&target, &guess, update)
блин, только что перечитал, увидел, что ты действительно их меняешь. Если меняешь (не понял пока логику, зачем), то ок, оставляй указателями

2023-07-12 16:43 UTC, AlexZav1327 commented on main.go
> +func main() {
Исправлено.

2023-07-12 16:45 UTC, AlexZav1327 commented on main.go
> +		fmt.Println("Error converting user response to integer:", err)
Вместо fmt.Println сделал logrus. Указанный код переделан
`func convertUserMessageToInt(message string) (int, bool) {
	notNumber := false

	result, err := strconv.Atoi(message)
	if err != nil {
		notNumber = true
	}

	return result, notNumber
}`

2023-07-12 16:47 UTC, AlexZav1327 commented on main.go
> +	case convertUserMessageToInt(userMessage) == *target:
Исправлено.

2023-07-12 16:58 UTC, AlexZav1327 commented on main.go
> +				g.processMessage(&target, &guess, update)
Я меняю target когда происходит событие: пользователь начал новую игру.
guess я меняю по мере уменьшения количества попыток на то, чтобы отгадать число, а также если началась новая игра.

2023-07-12 17:00 UTC, AlexZav1327 commented on main.go
> +				g.processCallbackQuery(&target, update)
Аналогично )
target меняется когда происходит событие: пользователь начал новую игру.
guess меняется по мере уменьшения количества попыток на то, чтобы отгадать число, а также если началась новая игра.

2023-07-14 12:12 UTC, AlexZav1327 commented on Makefile
> +lint:
Сделано )

2023-07-19 13:40 UTC, gerladeno requested changes

2023-07-19 13:40 UTC, gerladeno commented on internal/gameplay/game.go
> +func (g *GameSettings) HandleProcessMessage(userMessage string, target *int, guessLeft *int, guessLimit *int) (string, bool) { //nolint:lll
guessLeft и target сделай полями структуры, они должны быть внутри игры, зачем тебе это передаёт бот??

2023-07-19 13:40 UTC, gerladeno commented on internal/gameplay/game.go
> +	botAnswerOptions := map[string]string{
ты эту мапу создаёшь каждый раз при вызове этой функции. Хоть она потом и удаляется, поскольку на стеке, какой смысл её создавать каждый раз? Создай её отдельно, как неимпортируемую (т.е. глобальную в рамках пакета - это нормально), и к ней обращайся

2023-07-19 13:40 UTC, gerladeno commented on internal/gameplay/game.go
> +func (g *GameSettings) HandleProcessMessage(userMessage string, target *int, guessLeft *int, guessLimit *int) (string, bool) { //nolint:lll
а когда они станут полями структуры, ты избавишься от этих неуместных разыменований *target

2023-07-19 13:40 UTC, gerladeno commented on internal/gameplay/game.go
> +	return int(result)
ты осознаёшь, что в случае ошибки (да, она очень маловероятна) ты отдашь MinNum? Я не к тому, что это надо исправлять, но это надо осознавать.

2023-07-19 13:40 UTC, gerladeno commented on internal/gameplay/game.go
> +	userMessageAsInt, userMessageNotInt := convertUserMessageToInt(userMessage)
в го так не принято, верни тут честную ошибку

2023-07-19 13:40 UTC, gerladeno commented on internal/gameplay/game.go
> +	case userMessageNotInt:
а тут проверь err != nil

2023-07-19 13:40 UTC, gerladeno commented on internal/tg-bot/bot.go
> +func (b *GuessBot) processMessage(update tgbotapi.Update, target *int, guessLeft *int, guessLimit *int) {
сигнатура должна быть просто `func (b *GuessBot) processMessage(update tgbotapi.Update)`

2023-07-19 13:40 UTC, gerladeno commented on internal/tg-bot/bot.go
> +func (b *GuessBot) processCallbackQuery(update tgbotapi.Update, target *int, guessLeft *int, guessLimit *int) {
аналогично processMessage

2023-07-19 13:40 UTC, gerladeno commented on internal/tg-bot/bot.go
> +type GuessBot struct {
сделай все поля приватными

2023-07-19 19:35 UTC, AlexZav1327 commented on internal/gameplay/game.go
> +type Game struct {
Сделано

2023-07-19 19:35 UTC, AlexZav1327 commented on internal/gameplay/game.go
> +type GameSettings struct {
Сделано.

2023-07-19 19:36 UTC, AlexZav1327 commented on internal/gameplay/game.go
> +func (g *GameSettings) HandleProcessMessage(userMessage string, target *int, guessLeft *int, guessLimit *int) (string, bool) { //nolint:lll
Выполнено.

2023-07-19 19:36 UTC, AlexZav1327 commented on internal/gameplay/game.go
> +func (g *GameSettings) HandleProcessCallbackQuery(callbackData string, target *int, guessLeft *int, guessLimit *int) string { //nolint:lll
Выполнено.

2023-07-19 19:39 UTC, AlexZav1327 commented on internal/gameplay/game.go
> +func (g *GameSettings) generateRandNumb() int {
))) действительно как-то странно выглядит

2023-07-19 19:47 UTC, AlexZav1327 commented on internal/gameplay/game.go
> +	userMessageAsInt, userMessageNotInt := convertUserMessageToInt(userMessage)
Исправлено. Сделал намного проще, теперь функция convertUserMessageToInt вообще не нужна

2023-07-19 19:47 UTC, AlexZav1327 commented on internal/gameplay/game.go
> +	case userMessageNotInt:
Да.

2023-07-19 19:47 UTC, AlexZav1327 commented on internal/tg-bot/bot.go
> +func (b *GuessBot) processMessage(update tgbotapi.Update, target *int, guessLeft *int, guessLimit *int) {
Сделано.

2023-07-19 19:47 UTC, AlexZav1327 commented on internal/tg-bot/bot.go
> +func (b *GuessBot) processCallbackQuery(update tgbotapi.Update, target *int, guessLeft *int, guessLimit *int) {
Тоже сделано.

2023-07-19 19:48 UTC, AlexZav1327 commented on internal/tg-bot/bot.go
> +type GuessBot struct {
Сделано.

2023-07-19 19:50 UTC, AlexZav1327 commented on internal/gameplay/game.go
> +	return int(result)
Ты весьма наблюдательный ) Справедливое замечание. Может если `err != nil`, то делать панику

2023-07-19 20:31 UTC, AlexZav1327 commented on Makefile
> +	go build cmd/game/main.go
Теперь вот так выглядит:
```
build:
	go build -o bin/guess cmd/game/main.go
```

2023-07-19 20:35 UTC, AlexZav1327 commented on cmd/game/main.go
> +		}).Warning("BotAPI instance creation error")
Абсолютно справедливое замечание.

2023-07-19 20:37 UTC, AlexZav1327 commented on internal/gameplay/game.go
> +	Target    int
Исправлено.

2023-07-19 21:08 UTC, AlexZav1327 commented on cmd/game/main.go
> +	bot.Debug = true
Навел красоту ) добавил .bashrc `export DEBUG_MODE="true"`

2023-07-19 22:01 UTC, AlexZav1327 commented on cmd/game/main.go
> +	guessBot := tgbot.NewBot(updates, *bot, *game, *settings)
Не уверен, что так правильно, но выглядит так:
в gameplay 
```
type DefaultConfiguration struct {
	GuessLimit int
	MinNum     int
	MaxNum     int
}

func NewDefaultConfiguration() *DefaultConfiguration {
	return &DefaultConfiguration{
		GuessLimit: 10,
		MinNum:     1,
		MaxNum:     1000,
	}
}
```
в main
```
config := gameplay.NewDefaultConfiguration()
game := gameplay.NewGame(config.GuessLimit, gameplay.NewGameSettings(config.GuessLimit, config.MaxNum, config.MaxNum))
guessBot := tgbot.NewBot(updates, bot, game)
```

2023-07-19 22:07 UTC, AlexZav1327 commented on internal/gameplay/game.go
> +	botAnswerOptions := map[string]string{
В данном случае мапа должна иметь доступ к актуальным значениям guessLeft и target. Если я вынесу ее за пределы HandleProcessMessage, то не могу придумать адекватного способа передачи в нее сведений.

2023-07-19 22:38 UTC, gerladeno commented on internal/gameplay/game.go
> +	botAnswerOptions := map[string]string{
ну в совсем взрослых проектах это решается не мапами, но всё-таки
это просто означает, что тут надо оставить только текст. Например, "Твое число слишком БОЛЬШОЕ. Число оставшихся попыток: %d". А fmt.Sprintf должен вызывать код, который сюда обращается.

2023-07-19 22:38 UTC, gerladeno commented on internal/gameplay/game.go
> +	return int(result)
мб и правильно. Честно сказать, я не помню, почему это можеть дать ошибку, но если вдруг игра станет абсолютно прогнозируемой, то лучше упасть с паникой

2023-07-19 22:44 UTC, AlexZav1327 commented on internal/gameplay/game.go
> +	return int(result)
Спасибо )

2023-07-19 22:46 UTC, AlexZav1327 commented on internal/gameplay/game.go
> +	botAnswerOptions := map[string]string{
Понятно

2023-07-20 07:50 UTC, merged